/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AccountCreateEmailTokenRequest
 */
export interface AccountCreateEmailTokenRequest {
    /**
     * User ID. Choose a custom ID or generate a random ID with `ID.unique()`. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can\'t start with a special char. Max length is 36 chars.
     * @type {string}
     * @memberof AccountCreateEmailTokenRequest
     */
    'userId': string;
    /**
     * User email.
     * @type {string}
     * @memberof AccountCreateEmailTokenRequest
     */
    'email': string;
    /**
     * Toggle for security phrase. If enabled, email will be send with a randomly generated phrase and the phrase will also be included in the response. Confirming phrases match increases the security of your authentication flow.
     * @type {boolean}
     * @memberof AccountCreateEmailTokenRequest
     */
    'phrase'?: boolean;
}

