/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * AlgoArgon2
 * @export
 * @interface AlgoArgon2
 */
export interface AlgoArgon2 {
    /**
     * Algo type.
     * @type {string}
     * @memberof AlgoArgon2
     */
    'type': string;
    /**
     * Memory used to compute hash.
     * @type {number}
     * @memberof AlgoArgon2
     */
    'memoryCost': number;
    /**
     * Amount of time consumed to compute hash
     * @type {number}
     * @memberof AlgoArgon2
     */
    'timeCost': number;
    /**
     * Number of threads used to compute hash.
     * @type {number}
     * @memberof AlgoArgon2
     */
    'threads': number;
}

