/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * AttributeFloat
 * @export
 * @interface AttributeFloat
 */
export interface AttributeFloat {
    /**
     * Attribute Key.
     * @type {string}
     * @memberof AttributeFloat
     */
    'key': string;
    /**
     * Attribute type.
     * @type {string}
     * @memberof AttributeFloat
     */
    'type': string;
    /**
     * Attribute status. Possible values: `available`, `processing`, `deleting`, `stuck`, or `failed`
     * @type {string}
     * @memberof AttributeFloat
     */
    'status': string;
    /**
     * Error message. Displays error generated on failure of creating or deleting an attribute.
     * @type {string}
     * @memberof AttributeFloat
     */
    'error': string;
    /**
     * Is attribute required?
     * @type {boolean}
     * @memberof AttributeFloat
     */
    'required': boolean;
    /**
     * Is attribute an array?
     * @type {boolean}
     * @memberof AttributeFloat
     */
    'array'?: boolean | null;
    /**
     * Minimum value to enforce for new documents.
     * @type {number}
     * @memberof AttributeFloat
     */
    'min'?: number | null;
    /**
     * Maximum value to enforce for new documents.
     * @type {number}
     * @memberof AttributeFloat
     */
    'max'?: number | null;
    /**
     * Default value for attribute when not provided. Cannot be set when attribute is required.
     * @type {number}
     * @memberof AttributeFloat
     */
    'default'?: number | null;
    /**
     * Default value for attribute when not provided. Cannot be set when attribute is required.
     * @type {number}
     * @memberof AttributeFloat
     */
    'example'?: number | null;
    /**
     * Default value for attribute when not provided. Cannot be set when attribute is required.
     * @type {number}
     * @memberof AttributeFloat
     */
    'x-konfig-original-example'?: number | null;
}

