/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Bucket
 * @export
 * @interface Bucket
 */
export interface Bucket {
    /**
     * Bucket ID.
     * @type {string}
     * @memberof Bucket
     */
    '$id': string;
    /**
     * Bucket creation time in ISO 8601 format.
     * @type {string}
     * @memberof Bucket
     */
    '$createdAt': string;
    /**
     * Bucket update date in ISO 8601 format.
     * @type {string}
     * @memberof Bucket
     */
    '$updatedAt': string;
    /**
     * Bucket permissions. [Learn more about permissions](https://appwrite.io/docs/permissions).
     * @type {Array<string>}
     * @memberof Bucket
     */
    '$permissions': Array<string>;
    /**
     * Whether file-level security is enabled. [Learn more about permissions](https://appwrite.io/docs/permissions).
     * @type {boolean}
     * @memberof Bucket
     */
    'fileSecurity': boolean;
    /**
     * Bucket name.
     * @type {string}
     * @memberof Bucket
     */
    'name': string;
    /**
     * Bucket enabled.
     * @type {boolean}
     * @memberof Bucket
     */
    'enabled': boolean;
    /**
     * Maximum file size supported.
     * @type {number}
     * @memberof Bucket
     */
    'maximumFileSize': number;
    /**
     * Allowed file extensions.
     * @type {Array<string>}
     * @memberof Bucket
     */
    'allowedFileExtensions': Array<string>;
    /**
     * Compression algorithm choosen for compression. Will be one of none, [gzip](https://en.wikipedia.org/wiki/Gzip), or [zstd](https://en.wikipedia.org/wiki/Zstd).
     * @type {string}
     * @memberof Bucket
     */
    'compression': string;
    /**
     * Bucket is encrypted.
     * @type {boolean}
     * @memberof Bucket
     */
    'encryption': boolean;
    /**
     * Virus scanning is enabled.
     * @type {boolean}
     * @memberof Bucket
     */
    'antivirus': boolean;
}

