/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CollectionAttributesInner } from './collection-attributes-inner';
import { Index } from './index';

/**
 * Collection
 * @export
 * @interface Collection
 */
export interface Collection {
    /**
     * Collection ID.
     * @type {string}
     * @memberof Collection
     */
    '$id': string;
    /**
     * Collection creation date in ISO 8601 format.
     * @type {string}
     * @memberof Collection
     */
    '$createdAt': string;
    /**
     * Collection update date in ISO 8601 format.
     * @type {string}
     * @memberof Collection
     */
    '$updatedAt': string;
    /**
     * Collection permissions. [Learn more about permissions](https://appwrite.io/docs/permissions).
     * @type {Array<string>}
     * @memberof Collection
     */
    '$permissions': Array<string>;
    /**
     * Database ID.
     * @type {string}
     * @memberof Collection
     */
    'databaseId': string;
    /**
     * Collection name.
     * @type {string}
     * @memberof Collection
     */
    'name': string;
    /**
     * Collection enabled. Can be \'enabled\' or \'disabled\'. When disabled, the collection is inaccessible to users, but remains accessible to Server SDKs using API keys.
     * @type {boolean}
     * @memberof Collection
     */
    'enabled': boolean;
    /**
     * Whether document-level permissions are enabled. [Learn more about permissions](https://appwrite.io/docs/permissions).
     * @type {boolean}
     * @memberof Collection
     */
    'documentSecurity': boolean;
    /**
     * Collection attributes.
     * @type {Array<CollectionAttributesInner>}
     * @memberof Collection
     */
    'attributes': Array<CollectionAttributesInner>;
    /**
     * Collection indexes.
     * @type {Array<Index>}
     * @memberof Collection
     */
    'indexes': Array<Index>;
}

