/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Currency
 * @export
 * @interface Currency
 */
export interface Currency {
    /**
     * Currency symbol.
     * @type {string}
     * @memberof Currency
     */
    'symbol': string;
    /**
     * Currency name.
     * @type {string}
     * @memberof Currency
     */
    'name': string;
    /**
     * Currency native symbol.
     * @type {string}
     * @memberof Currency
     */
    'symbolNative': string;
    /**
     * Number of decimal digits.
     * @type {number}
     * @memberof Currency
     */
    'decimalDigits': number;
    /**
     * Currency digit rounding.
     * @type {number}
     * @memberof Currency
     */
    'rounding': number;
    /**
     * Currency code in [ISO 4217-1](http://en.wikipedia.org/wiki/ISO_4217) three-character format.
     * @type {string}
     * @memberof Currency
     */
    'code': string;
    /**
     * Currency plural name
     * @type {string}
     * @memberof Currency
     */
    'namePlural': string;
}

