/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabasesUpdateDocumentByIdRequest
 */
export interface DatabasesUpdateDocumentByIdRequest {
    /**
     * Document data as JSON object. Include only attribute and value pairs to be updated.
     * @type {object}
     * @memberof DatabasesUpdateDocumentByIdRequest
     */
    'data'?: object;
    /**
     * An array of permissions strings. By default, the current permissions are inherited. [Learn more about permissions](https://appwrite.io/docs/permissions).
     * @type {Array<string>}
     * @memberof DatabasesUpdateDocumentByIdRequest
     */
    'permissions'?: Array<string>;
}

