/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabasesCreateIndexRequest
 */
export interface DatabasesCreateIndexRequest {
    /**
     * Index Key.
     * @type {string}
     * @memberof DatabasesCreateIndexRequest
     */
    'key': string;
    /**
     * Index type.
     * @type {string}
     * @memberof DatabasesCreateIndexRequest
     */
    'type': DatabasesCreateIndexRequestTypeEnum;
    /**
     * Array of attributes to index. Maximum of 100 attributes are allowed, each 32 characters long.
     * @type {Array<string>}
     * @memberof DatabasesCreateIndexRequest
     */
    'attributes': Array<string>;
    /**
     * Array of index orders. Maximum of 100 orders are allowed.
     * @type {Array<string>}
     * @memberof DatabasesCreateIndexRequest
     */
    'orders'?: Array<string>;
}

type DatabasesCreateIndexRequestTypeEnum = 'key' | 'fulltext' | 'unique'


