/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Database
 * @export
 * @interface Database
 */
export interface Database {
    /**
     * Database ID.
     * @type {string}
     * @memberof Database
     */
    '$id': string;
    /**
     * Database name.
     * @type {string}
     * @memberof Database
     */
    'name': string;
    /**
     * Database creation date in ISO 8601 format.
     * @type {string}
     * @memberof Database
     */
    '$createdAt': string;
    /**
     * Database update date in ISO 8601 format.
     * @type {string}
     * @memberof Database
     */
    '$updatedAt': string;
    /**
     * If database is enabled. Can be \'enabled\' or \'disabled\'. When disabled, the database is inaccessible to users, but remains accessible to Server SDKs using API keys.
     * @type {boolean}
     * @memberof Database
     */
    'enabled': boolean;
}

