/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabasesUpdateFloatAttributeRequest
 */
export interface DatabasesUpdateFloatAttributeRequest {
    /**
     * Is attribute required?
     * @type {boolean}
     * @memberof DatabasesUpdateFloatAttributeRequest
     */
    'required': boolean;
    /**
     * Minimum value to enforce on new documents
     * @type {number}
     * @memberof DatabasesUpdateFloatAttributeRequest
     */
    'min': number;
    /**
     * Maximum value to enforce on new documents
     * @type {number}
     * @memberof DatabasesUpdateFloatAttributeRequest
     */
    'max': number;
    /**
     * Default value for attribute when not provided. Cannot be set when attribute is required.
     * @type {number}
     * @memberof DatabasesUpdateFloatAttributeRequest
     */
    'default': number;
}

