/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabasesCreateDatabaseRequest
 */
export interface DatabasesCreateDatabaseRequest {
    /**
     * Unique Id. Choose a custom ID or generate a random ID with `ID.unique()`. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can\'t start with a special char. Max length is 36 chars.
     * @type {string}
     * @memberof DatabasesCreateDatabaseRequest
     */
    'databaseId': string;
    /**
     * Database name. Max length: 128 chars.
     * @type {string}
     * @memberof DatabasesCreateDatabaseRequest
     */
    'name': string;
    /**
     * Is the database enabled? When set to \'disabled\', users cannot access the database but Server SDKs with an API key can still read and write to the database. No data is lost when this is toggled.
     * @type {boolean}
     * @memberof DatabasesCreateDatabaseRequest
     */
    'enabled'?: boolean;
}

