/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DatabasesCreateStringAttributeRequest
 */
export interface DatabasesCreateStringAttributeRequest {
    /**
     * Attribute Key.
     * @type {string}
     * @memberof DatabasesCreateStringAttributeRequest
     */
    'key': string;
    /**
     * Attribute size for text attributes, in number of characters.
     * @type {number}
     * @memberof DatabasesCreateStringAttributeRequest
     */
    'size': number;
    /**
     * Is attribute required?
     * @type {boolean}
     * @memberof DatabasesCreateStringAttributeRequest
     */
    'required': boolean;
    /**
     * Default value for attribute when not provided. Cannot be set when attribute is required.
     * @type {string}
     * @memberof DatabasesCreateStringAttributeRequest
     */
    'default'?: string;
    /**
     * Is attribute an array?
     * @type {boolean}
     * @memberof DatabasesCreateStringAttributeRequest
     */
    'array'?: boolean;
    /**
     * Toggle encryption for the attribute. Encryption enhances security by not storing any plain text values in the database. However, encrypted attributes cannot be queried.
     * @type {boolean}
     * @memberof DatabasesCreateStringAttributeRequest
     */
    'encrypt'?: boolean;
}

