/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Deployment
 * @export
 * @interface Deployment
 */
export interface Deployment {
    /**
     * Deployment ID.
     * @type {string}
     * @memberof Deployment
     */
    '$id': string;
    /**
     * Deployment creation date in ISO 8601 format.
     * @type {string}
     * @memberof Deployment
     */
    '$createdAt': string;
    /**
     * Deployment update date in ISO 8601 format.
     * @type {string}
     * @memberof Deployment
     */
    '$updatedAt': string;
    /**
     * Type of deployment.
     * @type {string}
     * @memberof Deployment
     */
    'type': string;
    /**
     * Resource ID.
     * @type {string}
     * @memberof Deployment
     */
    'resourceId': string;
    /**
     * Resource type.
     * @type {string}
     * @memberof Deployment
     */
    'resourceType': string;
    /**
     * The entrypoint file to use to execute the deployment code.
     * @type {string}
     * @memberof Deployment
     */
    'entrypoint': string;
    /**
     * The code size in bytes.
     * @type {number}
     * @memberof Deployment
     */
    'size': number;
    /**
     * The current build ID.
     * @type {string}
     * @memberof Deployment
     */
    'buildId': string;
    /**
     * Whether the deployment should be automatically activated.
     * @type {boolean}
     * @memberof Deployment
     */
    'activate': boolean;
    /**
     * The deployment status. Possible values are \"processing\", \"building\", \"waiting\", \"ready\", and \"failed\".
     * @type {string}
     * @memberof Deployment
     */
    'status': string;
    /**
     * The build logs.
     * @type {string}
     * @memberof Deployment
     */
    'buildLogs': string;
    /**
     * The current build time in seconds.
     * @type {number}
     * @memberof Deployment
     */
    'buildTime': number;
    /**
     * The name of the vcs provider repository
     * @type {string}
     * @memberof Deployment
     */
    'providerRepositoryName': string;
    /**
     * The name of the vcs provider repository owner
     * @type {string}
     * @memberof Deployment
     */
    'providerRepositoryOwner': string;
    /**
     * The url of the vcs provider repository
     * @type {string}
     * @memberof Deployment
     */
    'providerRepositoryUrl': string;
    /**
     * The branch of the vcs repository
     * @type {string}
     * @memberof Deployment
     */
    'providerBranch': string;
    /**
     * The commit hash of the vcs commit
     * @type {string}
     * @memberof Deployment
     */
    'providerCommitHash': string;
    /**
     * The url of vcs commit author
     * @type {string}
     * @memberof Deployment
     */
    'providerCommitAuthorUrl': string;
    /**
     * The name of vcs commit author
     * @type {string}
     * @memberof Deployment
     */
    'providerCommitAuthor': string;
    /**
     * The commit message
     * @type {string}
     * @memberof Deployment
     */
    'providerCommitMessage': string;
    /**
     * The url of the vcs commit
     * @type {string}
     * @memberof Deployment
     */
    'providerCommitUrl': string;
    /**
     * The branch of the vcs repository
     * @type {string}
     * @memberof Deployment
     */
    'providerBranchUrl': string;
}

