/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Document
 * @export
 * @interface Document
 */
export interface Document {
    [key: string]: any;

    /**
     * Document ID.
     * @type {string}
     * @memberof Document
     */
    '$id': string;
    /**
     * Collection ID.
     * @type {string}
     * @memberof Document
     */
    '$collectionId': string;
    /**
     * Database ID.
     * @type {string}
     * @memberof Document
     */
    '$databaseId': string;
    /**
     * Document creation date in ISO 8601 format.
     * @type {string}
     * @memberof Document
     */
    '$createdAt': string;
    /**
     * Document update date in ISO 8601 format.
     * @type {string}
     * @memberof Document
     */
    '$updatedAt': string;
    /**
     * Document permissions. [Learn more about permissions](https://appwrite.io/docs/permissions).
     * @type {Array<string>}
     * @memberof Document
     */
    '$permissions': Array<string>;
}

