/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Headers } from './headers';

/**
 * Execution
 * @export
 * @interface Execution
 */
export interface Execution {
    /**
     * Execution ID.
     * @type {string}
     * @memberof Execution
     */
    '$id': string;
    /**
     * Execution creation date in ISO 8601 format.
     * @type {string}
     * @memberof Execution
     */
    '$createdAt': string;
    /**
     * Execution upate date in ISO 8601 format.
     * @type {string}
     * @memberof Execution
     */
    '$updatedAt': string;
    /**
     * Execution roles.
     * @type {Array<string>}
     * @memberof Execution
     */
    '$permissions': Array<string>;
    /**
     * Function ID.
     * @type {string}
     * @memberof Execution
     */
    'functionId': string;
    /**
     * The trigger that caused the function to execute. Possible values can be: `http`, `schedule`, or `event`.
     * @type {string}
     * @memberof Execution
     */
    'trigger': string;
    /**
     * The status of the function execution. Possible values can be: `waiting`, `processing`, `completed`, or `failed`.
     * @type {string}
     * @memberof Execution
     */
    'status': string;
    /**
     * HTTP request method type.
     * @type {string}
     * @memberof Execution
     */
    'requestMethod': string;
    /**
     * HTTP request path and query.
     * @type {string}
     * @memberof Execution
     */
    'requestPath': string;
    /**
     * HTTP response headers as a key-value object. This will return only whitelisted headers. All headers are returned if execution is created as synchronous.
     * @type {Array<Headers>}
     * @memberof Execution
     */
    'requestHeaders': Array<Headers>;
    /**
     * HTTP response status code.
     * @type {number}
     * @memberof Execution
     */
    'responseStatusCode': number;
    /**
     * HTTP response body. This will return empty unless execution is created as synchronous.
     * @type {string}
     * @memberof Execution
     */
    'responseBody': string;
    /**
     * HTTP response headers as a key-value object. This will return only whitelisted headers. All headers are returned if execution is created as synchronous.
     * @type {Array<Headers>}
     * @memberof Execution
     */
    'responseHeaders': Array<Headers>;
    /**
     * Function logs. Includes the last 4,000 characters. This will return an empty string unless the response is returned using an API key or as part of a webhook payload.
     * @type {string}
     * @memberof Execution
     */
    'logs': string;
    /**
     * Function errors. Includes the last 4,000 characters. This will return an empty string unless the response is returned using an API key or as part of a webhook payload.
     * @type {string}
     * @memberof Execution
     */
    'errors': string;
    /**
     * Function execution duration in seconds.
     * @type {number}
     * @memberof Execution
     */
    'duration': number;
}

