/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FunctionsCreateDeploymentFunctionCodeRequest
 */
export interface FunctionsCreateDeploymentFunctionCodeRequest {
    /**
     * Entrypoint File.
     * @type {string}
     * @memberof FunctionsCreateDeploymentFunctionCodeRequest
     */
    'entrypoint'?: string;
    /**
     * Build Commands.
     * @type {string}
     * @memberof FunctionsCreateDeploymentFunctionCodeRequest
     */
    'commands'?: string;
    /**
     * Gzip file with your code package. When used with the Appwrite CLI, pass the path to your code directory, and the CLI will automatically package your code. Use a path that is within the current directory.
     * @type {string}
     * @memberof FunctionsCreateDeploymentFunctionCodeRequest
     */
    'code': string;
    /**
     * Automatically activate the deployment when it is finished building.
     * @type {boolean}
     * @memberof FunctionsCreateDeploymentFunctionCodeRequest
     */
    'activate': boolean;
}

