/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Variable } from './variable';

/**
 * Function
 * @export
 * @interface Function
 */
export interface Function {
    /**
     * Version of Open Runtimes used for the function.
     * @type {string}
     * @memberof Function
     */
    'version': string;
    /**
     * Function ID.
     * @type {string}
     * @memberof Function
     */
    '$id': string;
    /**
     * Function creation date in ISO 8601 format.
     * @type {string}
     * @memberof Function
     */
    '$createdAt': string;
    /**
     * Function update date in ISO 8601 format.
     * @type {string}
     * @memberof Function
     */
    '$updatedAt': string;
    /**
     * Execution permissions.
     * @type {Array<string>}
     * @memberof Function
     */
    'execute': Array<string>;
    /**
     * Function name.
     * @type {string}
     * @memberof Function
     */
    'name': string;
    /**
     * Function enabled.
     * @type {boolean}
     * @memberof Function
     */
    'enabled': boolean;
    /**
     * Is the function deployed with the latest configuration? This is set to false if you\'ve changed an environment variables, entrypoint, commands, or other settings that needs redeploy to be applied. When the value is false, redeploy the function to update it with the latest configuration.
     * @type {boolean}
     * @memberof Function
     */
    'live': boolean;
    /**
     * Whether executions will be logged. When set to false, executions will not be logged, but will reduce resource used by your Appwrite project.
     * @type {boolean}
     * @memberof Function
     */
    'logging': boolean;
    /**
     * Function execution runtime.
     * @type {string}
     * @memberof Function
     */
    'runtime': string;
    /**
     * Function\'s active deployment ID.
     * @type {string}
     * @memberof Function
     */
    'deployment': string;
    /**
     * Function variables.
     * @type {Array<Variable>}
     * @memberof Function
     */
    'vars': Array<Variable>;
    /**
     * Function trigger events.
     * @type {Array<string>}
     * @memberof Function
     */
    'events': Array<string>;
    /**
     * Function execution schedult in CRON format.
     * @type {string}
     * @memberof Function
     */
    'schedule': string;
    /**
     * Function execution timeout in seconds.
     * @type {number}
     * @memberof Function
     */
    'timeout': number;
    /**
     * The entrypoint file used to execute the deployment.
     * @type {string}
     * @memberof Function
     */
    'entrypoint': string;
    /**
     * The build command used to build the deployment.
     * @type {string}
     * @memberof Function
     */
    'commands': string;
    /**
     * Function VCS (Version Control System) installation id.
     * @type {string}
     * @memberof Function
     */
    'installationId': string;
    /**
     * VCS (Version Control System) Repository ID
     * @type {string}
     * @memberof Function
     */
    'providerRepositoryId': string;
    /**
     * VCS (Version Control System) branch name
     * @type {string}
     * @memberof Function
     */
    'providerBranch': string;
    /**
     * Path to function in VCS (Version Control System) repository
     * @type {string}
     * @memberof Function
     */
    'providerRootDirectory': string;
    /**
     * Is VCS (Version Control System) connection is in silent mode? When in silence mode, no comments will be posted on the repository pull or merge requests
     * @type {boolean}
     * @memberof Function
     */
    'providerSilentMode': boolean;
}

