/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Health Status
 * @export
 * @interface HealthStatus
 */
export interface HealthStatus {
    /**
     * Name of the service.
     * @type {string}
     * @memberof HealthStatus
     */
    'name': string;
    /**
     * Duration in milliseconds how long the health check took.
     * @type {number}
     * @memberof HealthStatus
     */
    'ping': number;
    /**
     * Service status. Possible values can are: `pass`, `fail`
     * @type {string}
     * @memberof HealthStatus
     */
    'status': string;
}

