/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Identity
 * @export
 * @interface Identity
 */
export interface Identity {
    /**
     * Identity ID.
     * @type {string}
     * @memberof Identity
     */
    '$id': string;
    /**
     * Identity creation date in ISO 8601 format.
     * @type {string}
     * @memberof Identity
     */
    '$createdAt': string;
    /**
     * Identity update date in ISO 8601 format.
     * @type {string}
     * @memberof Identity
     */
    '$updatedAt': string;
    /**
     * User ID.
     * @type {string}
     * @memberof Identity
     */
    'userId': string;
    /**
     * Identity Provider.
     * @type {string}
     * @memberof Identity
     */
    'provider': string;
    /**
     * ID of the User in the Identity Provider.
     * @type {string}
     * @memberof Identity
     */
    'providerUid': string;
    /**
     * Email of the User in the Identity Provider.
     * @type {string}
     * @memberof Identity
     */
    'providerEmail': string;
    /**
     * Identity Provider Access Token.
     * @type {string}
     * @memberof Identity
     */
    'providerAccessToken': string;
    /**
     * The date of when the access token expires in ISO 8601 format.
     * @type {string}
     * @memberof Identity
     */
    'providerAccessTokenExpiry': string;
    /**
     * Identity Provider Refresh Token.
     * @type {string}
     * @memberof Identity
     */
    'providerRefreshToken': string;
}

