/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Locale
 * @export
 * @interface Locale
 */
export interface Locale {
    /**
     * User IP address.
     * @type {string}
     * @memberof Locale
     */
    'ip': string;
    /**
     * Country code in [ISO 3166-1](http://en.wikipedia.org/wiki/ISO_3166-1) two-character format
     * @type {string}
     * @memberof Locale
     */
    'countryCode': string;
    /**
     * Country name. This field support localization.
     * @type {string}
     * @memberof Locale
     */
    'country': string;
    /**
     * Continent code. A two character continent code \"AF\" for Africa, \"AN\" for Antarctica, \"AS\" for Asia, \"EU\" for Europe, \"NA\" for North America, \"OC\" for Oceania, and \"SA\" for South America.
     * @type {string}
     * @memberof Locale
     */
    'continentCode': string;
    /**
     * Continent name. This field support localization.
     * @type {string}
     * @memberof Locale
     */
    'continent': string;
    /**
     * True if country is part of the European Union.
     * @type {boolean}
     * @memberof Locale
     */
    'eu': boolean;
    /**
     * Currency code in [ISO 4217-1](http://en.wikipedia.org/wiki/ISO_4217) three-character format
     * @type {string}
     * @memberof Locale
     */
    'currency': string;
}

