/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * LocaleCode
 * @export
 * @interface LocaleCode
 */
export interface LocaleCode {
    /**
     * Locale codes in [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
     * @type {string}
     * @memberof LocaleCode
     */
    'code': string;
    /**
     * Locale name
     * @type {string}
     * @memberof LocaleCode
     */
    'name': string;
}

