/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Membership
 * @export
 * @interface Membership
 */
export interface Membership {
    /**
     * Membership ID.
     * @type {string}
     * @memberof Membership
     */
    '$id': string;
    /**
     * Membership creation date in ISO 8601 format.
     * @type {string}
     * @memberof Membership
     */
    '$createdAt': string;
    /**
     * Membership update date in ISO 8601 format.
     * @type {string}
     * @memberof Membership
     */
    '$updatedAt': string;
    /**
     * User ID.
     * @type {string}
     * @memberof Membership
     */
    'userId': string;
    /**
     * User name.
     * @type {string}
     * @memberof Membership
     */
    'userName': string;
    /**
     * User email address.
     * @type {string}
     * @memberof Membership
     */
    'userEmail': string;
    /**
     * Team ID.
     * @type {string}
     * @memberof Membership
     */
    'teamId': string;
    /**
     * Team name.
     * @type {string}
     * @memberof Membership
     */
    'teamName': string;
    /**
     * Date, the user has been invited to join the team in ISO 8601 format.
     * @type {string}
     * @memberof Membership
     */
    'invited': string;
    /**
     * Date, the user has accepted the invitation to join the team in ISO 8601 format.
     * @type {string}
     * @memberof Membership
     */
    'joined': string;
    /**
     * User confirmation status, true if the user has joined the team or false otherwise.
     * @type {boolean}
     * @memberof Membership
     */
    'confirm': boolean;
    /**
     * Multi factor authentication status, true if the user has MFA enabled or false otherwise.
     * @type {boolean}
     * @memberof Membership
     */
    'mfa': boolean;
    /**
     * User list of roles
     * @type {Array<string>}
     * @memberof Membership
     */
    'roles': Array<string>;
}

