/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MessagingCreateApnsProviderRequest
 */
export interface MessagingCreateApnsProviderRequest {
    /**
     * Provider ID. Choose a custom ID or generate a random ID with `ID.unique()`. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can\'t start with a special char. Max length is 36 chars.
     * @type {string}
     * @memberof MessagingCreateApnsProviderRequest
     */
    'providerId': string;
    /**
     * Provider name.
     * @type {string}
     * @memberof MessagingCreateApnsProviderRequest
     */
    'name': string;
    /**
     * APNS authentication key.
     * @type {string}
     * @memberof MessagingCreateApnsProviderRequest
     */
    'authKey'?: string;
    /**
     * APNS authentication key ID.
     * @type {string}
     * @memberof MessagingCreateApnsProviderRequest
     */
    'authKeyId'?: string;
    /**
     * APNS team ID.
     * @type {string}
     * @memberof MessagingCreateApnsProviderRequest
     */
    'teamId'?: string;
    /**
     * APNS bundle ID.
     * @type {string}
     * @memberof MessagingCreateApnsProviderRequest
     */
    'bundleId'?: string;
    /**
     * Use APNS sandbox environment.
     * @type {boolean}
     * @memberof MessagingCreateApnsProviderRequest
     */
    'sandbox'?: boolean;
    /**
     * Set as enabled.
     * @type {boolean}
     * @memberof MessagingCreateApnsProviderRequest
     */
    'enabled'?: boolean;
}

