/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MessagingUpdateSmsMessageRequest
 */
export interface MessagingUpdateSmsMessageRequest {
    /**
     * List of Topic IDs.
     * @type {Array<string>}
     * @memberof MessagingUpdateSmsMessageRequest
     */
    'topics'?: Array<string>;
    /**
     * List of User IDs.
     * @type {Array<string>}
     * @memberof MessagingUpdateSmsMessageRequest
     */
    'users'?: Array<string>;
    /**
     * List of Targets IDs.
     * @type {Array<string>}
     * @memberof MessagingUpdateSmsMessageRequest
     */
    'targets'?: Array<string>;
    /**
     * Email Content.
     * @type {string}
     * @memberof MessagingUpdateSmsMessageRequest
     */
    'content'?: string;
    /**
     * Is message a draft
     * @type {boolean}
     * @memberof MessagingUpdateSmsMessageRequest
     */
    'draft'?: boolean;
    /**
     * Scheduled delivery time for message in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format. DateTime value must be in future.
     * @type {string}
     * @memberof MessagingUpdateSmsMessageRequest
     */
    'scheduledAt'?: string;
}

