/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MessagingCreateEmailMessageRequest
 */
export interface MessagingCreateEmailMessageRequest {
    /**
     * Message ID. Choose a custom ID or generate a random ID with `ID.unique()`. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can\'t start with a special char. Max length is 36 chars.
     * @type {string}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'messageId': string;
    /**
     * Email Subject.
     * @type {string}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'subject': string;
    /**
     * Email Content.
     * @type {string}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'content': string;
    /**
     * List of Topic IDs.
     * @type {Array<string>}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'topics'?: Array<string>;
    /**
     * List of User IDs.
     * @type {Array<string>}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'users'?: Array<string>;
    /**
     * List of Targets IDs.
     * @type {Array<string>}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'targets'?: Array<string>;
    /**
     * Array of target IDs to be added as CC.
     * @type {Array<string>}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'cc'?: Array<string>;
    /**
     * Array of target IDs to be added as BCC.
     * @type {Array<string>}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'bcc'?: Array<string>;
    /**
     * Array of compound bucket IDs to file IDs to be attached to the email.
     * @type {Array<string>}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'attachments'?: Array<string>;
    /**
     * Is message a draft
     * @type {boolean}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'draft'?: boolean;
    /**
     * Is content of type HTML
     * @type {boolean}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'html'?: boolean;
    /**
     * Scheduled delivery time for message in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format. DateTime value must be in future.
     * @type {string}
     * @memberof MessagingCreateEmailMessageRequest
     */
    'scheduledAt'?: string;
}

