/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MessagingCreatePushNotificationRequest
 */
export interface MessagingCreatePushNotificationRequest {
    /**
     * Title for push notification.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'title': string;
    /**
     * Message ID. Choose a custom ID or generate a random ID with `ID.unique()`. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can\'t start with a special char. Max length is 36 chars.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'messageId': string;
    /**
     * Body for push notification.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'body': string;
    /**
     * List of Topic IDs.
     * @type {Array<string>}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'topics'?: Array<string>;
    /**
     * List of User IDs.
     * @type {Array<string>}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'users'?: Array<string>;
    /**
     * List of Targets IDs.
     * @type {Array<string>}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'targets'?: Array<string>;
    /**
     * Additional Data for push notification.
     * @type {object}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'data'?: object;
    /**
     * Action for push notification.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'action'?: string;
    /**
     * Image for push notification. Must be a compound bucket ID to file ID of a jpeg, png, or bmp image in Appwrite Storage.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'image'?: string;
    /**
     * Icon for push notification. Available only for Android and Web Platform.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'icon'?: string;
    /**
     * Sound for push notification. Available only for Android and IOS Platform.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'sound'?: string;
    /**
     * Color for push notification. Available only for Android Platform.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'color'?: string;
    /**
     * Tag for push notification. Available only for Android Platform.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'tag'?: string;
    /**
     * Badge for push notification. Available only for IOS Platform.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'badge'?: string;
    /**
     * Is message a draft
     * @type {boolean}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'draft'?: boolean;
    /**
     * Scheduled delivery time for message in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format. DateTime value must be in future.
     * @type {string}
     * @memberof MessagingCreatePushNotificationRequest
     */
    'scheduledAt'?: string;
}

