/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MessagingUpdateProviderByIdRequest
 */
export interface MessagingUpdateProviderByIdRequest {
    /**
     * Provider name.
     * @type {string}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'name'?: string;
    /**
     * SMTP hosts. Either a single hostname or multiple semicolon-delimited hostnames. You can also specify a different port for each host such as `smtp1.example.com:25;smtp2.example.com`. You can also specify encryption type, for example: `tls://smtp1.example.com:587;ssl://smtp2.example.com:465\"`. Hosts will be tried in order.
     * @type {string}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'host'?: string;
    /**
     * SMTP port.
     * @type {number}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'port'?: number;
    /**
     * Authentication username.
     * @type {string}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'username'?: string;
    /**
     * Authentication password.
     * @type {string}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'password'?: string;
    /**
     * Encryption type. Can be \'ssl\' or \'tls\'
     * @type {string}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'encryption'?: MessagingUpdateProviderByIdRequestEncryptionEnum;
    /**
     * Enable SMTP AutoTLS feature.
     * @type {boolean}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'autoTLS'?: boolean;
    /**
     * The value to use for the X-Mailer header.
     * @type {string}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'mailer'?: string;
    /**
     * Sender Name.
     * @type {string}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'fromName'?: string;
    /**
     * Sender email address.
     * @type {string}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'fromEmail'?: string;
    /**
     * Name set in the Reply To field for the mail. Default value is Sender Name.
     * @type {string}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'replyToName'?: string;
    /**
     * Email set in the Reply To field for the mail. Default value is Sender Email.
     * @type {string}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'replyToEmail'?: string;
    /**
     * Set as enabled.
     * @type {boolean}
     * @memberof MessagingUpdateProviderByIdRequest
     */
    'enabled'?: boolean;
}

type MessagingUpdateProviderByIdRequestEncryptionEnum = 'none' | 'ssl' | 'tls'


