/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MessagingUpdateApnsProviderRequest
 */
export interface MessagingUpdateApnsProviderRequest {
    /**
     * Provider name.
     * @type {string}
     * @memberof MessagingUpdateApnsProviderRequest
     */
    'name'?: string;
    /**
     * Set as enabled.
     * @type {boolean}
     * @memberof MessagingUpdateApnsProviderRequest
     */
    'enabled'?: boolean;
    /**
     * APNS authentication key.
     * @type {string}
     * @memberof MessagingUpdateApnsProviderRequest
     */
    'authKey'?: string;
    /**
     * APNS authentication key ID.
     * @type {string}
     * @memberof MessagingUpdateApnsProviderRequest
     */
    'authKeyId'?: string;
    /**
     * APNS team ID.
     * @type {string}
     * @memberof MessagingUpdateApnsProviderRequest
     */
    'teamId'?: string;
    /**
     * APNS bundle ID.
     * @type {string}
     * @memberof MessagingUpdateApnsProviderRequest
     */
    'bundleId'?: string;
    /**
     * Use APNS sandbox environment.
     * @type {boolean}
     * @memberof MessagingUpdateApnsProviderRequest
     */
    'sandbox'?: boolean;
}

