/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * File
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
    /**
     * File ID.
     * @type {string}
     * @memberof ModelFile
     */
    '$id': string;
    /**
     * Bucket ID.
     * @type {string}
     * @memberof ModelFile
     */
    'bucketId': string;
    /**
     * File creation date in ISO 8601 format.
     * @type {string}
     * @memberof ModelFile
     */
    '$createdAt': string;
    /**
     * File update date in ISO 8601 format.
     * @type {string}
     * @memberof ModelFile
     */
    '$updatedAt': string;
    /**
     * File permissions. [Learn more about permissions](https://appwrite.io/docs/permissions).
     * @type {Array<string>}
     * @memberof ModelFile
     */
    '$permissions': Array<string>;
    /**
     * File name.
     * @type {string}
     * @memberof ModelFile
     */
    'name': string;
    /**
     * File MD5 signature.
     * @type {string}
     * @memberof ModelFile
     */
    'signature': string;
    /**
     * File mime type.
     * @type {string}
     * @memberof ModelFile
     */
    'mimeType': string;
    /**
     * File original size in bytes.
     * @type {number}
     * @memberof ModelFile
     */
    'sizeOriginal': number;
    /**
     * Total number of chunks available
     * @type {number}
     * @memberof ModelFile
     */
    'chunksTotal': number;
    /**
     * Total number of chunks uploaded
     * @type {number}
     * @memberof ModelFile
     */
    'chunksUploaded': number;
}

