/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Provider
 * @export
 * @interface Provider
 */
export interface Provider {
    /**
     * Provider ID.
     * @type {string}
     * @memberof Provider
     */
    '$id': string;
    /**
     * Provider creation time in ISO 8601 format.
     * @type {string}
     * @memberof Provider
     */
    '$createdAt': string;
    /**
     * Provider update date in ISO 8601 format.
     * @type {string}
     * @memberof Provider
     */
    '$updatedAt': string;
    /**
     * The name for the provider instance.
     * @type {string}
     * @memberof Provider
     */
    'name': string;
    /**
     * The name of the provider service.
     * @type {string}
     * @memberof Provider
     */
    'provider': string;
    /**
     * Is provider enabled?
     * @type {boolean}
     * @memberof Provider
     */
    'enabled': boolean;
    /**
     * Type of provider.
     * @type {string}
     * @memberof Provider
     */
    'type': string;
    /**
     * Provider credentials.
     * @type {object}
     * @memberof Provider
     */
    'credentials': object;
    /**
     * Provider options.
     * @type {object}
     * @memberof Provider
     */
    'options'?: object | null;
}

