/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Runtime } from './runtime';

/**
 * Runtimes List
 * @export
 * @interface RuntimeList
 */
export interface RuntimeList {
    /**
     * Total number of runtimes documents that matched your query.
     * @type {number}
     * @memberof RuntimeList
     */
    'total': number;
    /**
     * List of runtimes.
     * @type {Array<Runtime>}
     * @memberof RuntimeList
     */
    'runtimes': Array<Runtime>;
}

