/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Session
 * @export
 * @interface Session
 */
export interface Session {
    /**
     * Session ID.
     * @type {string}
     * @memberof Session
     */
    '$id': string;
    /**
     * Session creation date in ISO 8601 format.
     * @type {string}
     * @memberof Session
     */
    '$createdAt': string;
    /**
     * User ID.
     * @type {string}
     * @memberof Session
     */
    'userId': string;
    /**
     * Session expiration date in ISO 8601 format.
     * @type {string}
     * @memberof Session
     */
    'expire': string;
    /**
     * Session Provider.
     * @type {string}
     * @memberof Session
     */
    'provider': string;
    /**
     * Session Provider User ID.
     * @type {string}
     * @memberof Session
     */
    'providerUid': string;
    /**
     * Session Provider Access Token.
     * @type {string}
     * @memberof Session
     */
    'providerAccessToken': string;
    /**
     * The date of when the access token expires in ISO 8601 format.
     * @type {string}
     * @memberof Session
     */
    'providerAccessTokenExpiry': string;
    /**
     * Session Provider Refresh Token.
     * @type {string}
     * @memberof Session
     */
    'providerRefreshToken': string;
    /**
     * IP in use when the session was created.
     * @type {string}
     * @memberof Session
     */
    'ip': string;
    /**
     * Operating system code name. View list of [available options](https://github.com/appwrite/appwrite/blob/master/docs/lists/os.json).
     * @type {string}
     * @memberof Session
     */
    'osCode': string;
    /**
     * Operating system name.
     * @type {string}
     * @memberof Session
     */
    'osName': string;
    /**
     * Operating system version.
     * @type {string}
     * @memberof Session
     */
    'osVersion': string;
    /**
     * Client type.
     * @type {string}
     * @memberof Session
     */
    'clientType': string;
    /**
     * Client code name. View list of [available options](https://github.com/appwrite/appwrite/blob/master/docs/lists/clients.json).
     * @type {string}
     * @memberof Session
     */
    'clientCode': string;
    /**
     * Client name.
     * @type {string}
     * @memberof Session
     */
    'clientName': string;
    /**
     * Client version.
     * @type {string}
     * @memberof Session
     */
    'clientVersion': string;
    /**
     * Client engine name.
     * @type {string}
     * @memberof Session
     */
    'clientEngine': string;
    /**
     * Client engine name.
     * @type {string}
     * @memberof Session
     */
    'clientEngineVersion': string;
    /**
     * Device name.
     * @type {string}
     * @memberof Session
     */
    'deviceName': string;
    /**
     * Device brand name.
     * @type {string}
     * @memberof Session
     */
    'deviceBrand': string;
    /**
     * Device model name.
     * @type {string}
     * @memberof Session
     */
    'deviceModel': string;
    /**
     * Country two-character ISO 3166-1 alpha code.
     * @type {string}
     * @memberof Session
     */
    'countryCode': string;
    /**
     * Country name.
     * @type {string}
     * @memberof Session
     */
    'countryName': string;
    /**
     * Returns true if this the current user session.
     * @type {boolean}
     * @memberof Session
     */
    'current': boolean;
    /**
     * Returns a list of active session factors.
     * @type {Array<string>}
     * @memberof Session
     */
    'factors': Array<string>;
    /**
     * Secret used to authenticate the user. Only included if the request was made with an API key
     * @type {string}
     * @memberof Session
     */
    'secret': string;
    /**
     * Most recent date in ISO 8601 format when the session successfully passed MFA challenge.
     * @type {string}
     * @memberof Session
     */
    'mfaUpdatedAt': string;
}

