/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface StorageCreateNewBucketRequest
 */
export interface StorageCreateNewBucketRequest {
    /**
     * Unique Id. Choose a custom ID or generate a random ID with `ID.unique()`. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can\'t start with a special char. Max length is 36 chars.
     * @type {string}
     * @memberof StorageCreateNewBucketRequest
     */
    'bucketId': string;
    /**
     * Bucket name
     * @type {string}
     * @memberof StorageCreateNewBucketRequest
     */
    'name': string;
    /**
     * An array of permission strings. By default, no user is granted with any permissions. [Learn more about permissions](https://appwrite.io/docs/permissions).
     * @type {Array<string>}
     * @memberof StorageCreateNewBucketRequest
     */
    'permissions'?: Array<string>;
    /**
     * Enables configuring permissions for individual file. A user needs one of file or bucket level permissions to access a file. [Learn more about permissions](https://appwrite.io/docs/permissions).
     * @type {boolean}
     * @memberof StorageCreateNewBucketRequest
     */
    'fileSecurity'?: boolean;
    /**
     * Is bucket enabled? When set to \'disabled\', users cannot access the files in this bucket but Server SDKs with and API key can still access the bucket. No files are lost when this is toggled.
     * @type {boolean}
     * @memberof StorageCreateNewBucketRequest
     */
    'enabled'?: boolean;
    /**
     * Maximum file size allowed in bytes. Maximum allowed value is 30MB.
     * @type {number}
     * @memberof StorageCreateNewBucketRequest
     */
    'maximumFileSize'?: number;
    /**
     * Allowed file extensions. Maximum of 100 extensions are allowed, each 64 characters long.
     * @type {Array<string>}
     * @memberof StorageCreateNewBucketRequest
     */
    'allowedFileExtensions'?: Array<string>;
    /**
     * Compression algorithm choosen for compression. Can be one of none,  [gzip](https://en.wikipedia.org/wiki/Gzip), or [zstd](https://en.wikipedia.org/wiki/Zstd), For file size above 20MB compression is skipped even if it\'s enabled
     * @type {string}
     * @memberof StorageCreateNewBucketRequest
     */
    'compression'?: StorageCreateNewBucketRequestCompressionEnum;
    /**
     * Is encryption enabled? For file size above 20MB encryption is skipped even if it\'s enabled
     * @type {boolean}
     * @memberof StorageCreateNewBucketRequest
     */
    'encryption'?: boolean;
    /**
     * Is virus scanning enabled? For file size above 20MB AntiVirus scanning is skipped even if it\'s enabled
     * @type {boolean}
     * @memberof StorageCreateNewBucketRequest
     */
    'antivirus'?: boolean;
}

type StorageCreateNewBucketRequestCompressionEnum = 'none' | 'gzip' | 'zstd'


