/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Team
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * Team ID.
     * @type {string}
     * @memberof Team
     */
    '$id': string;
    /**
     * Team creation date in ISO 8601 format.
     * @type {string}
     * @memberof Team
     */
    '$createdAt': string;
    /**
     * Team update date in ISO 8601 format.
     * @type {string}
     * @memberof Team
     */
    '$updatedAt': string;
    /**
     * Team name.
     * @type {string}
     * @memberof Team
     */
    'name': string;
    /**
     * Total number of team members.
     * @type {number}
     * @memberof Team
     */
    'total': number;
    /**
     * Team preferences as a key-value object
     * @type {Array<{ [key: string]: any; }>}
     * @memberof Team
     */
    'prefs': Array<{ [key: string]: any; }>;
}

