/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TeamsCreateMembershipRequestRequest
 */
export interface TeamsCreateMembershipRequestRequest {
    /**
     * Email of the new team member.
     * @type {string}
     * @memberof TeamsCreateMembershipRequestRequest
     */
    'email'?: string;
    /**
     * ID of the user to be added to a team.
     * @type {string}
     * @memberof TeamsCreateMembershipRequestRequest
     */
    'userId'?: string;
    /**
     * Phone number. Format this number with a leading \'+\' and a country code, e.g., +16175551212.
     * @type {string}
     * @memberof TeamsCreateMembershipRequestRequest
     */
    'phone'?: string;
    /**
     * Array of strings. Use this param to set the user roles in the team. A role can be any string. Learn more about [roles and permissions](https://appwrite.io/docs/permissions). Maximum of 100 roles are allowed, each 32 characters long.
     * @type {Array<string>}
     * @memberof TeamsCreateMembershipRequestRequest
     */
    'roles': Array<string>;
    /**
     * URL to redirect the user back to your app from the invitation email.  Only URLs from hostnames in your project platform list are allowed. This requirement helps to prevent an [open redirect](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html) attack against your project API.
     * @type {string}
     * @memberof TeamsCreateMembershipRequestRequest
     */
    'url'?: string;
    /**
     * Name of the new team member. Max length: 128 chars.
     * @type {string}
     * @memberof TeamsCreateMembershipRequestRequest
     */
    'name'?: string;
}

