/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TeamsCreateNewTeamRequest
 */
export interface TeamsCreateNewTeamRequest {
    /**
     * Team ID. Choose a custom ID or generate a random ID with `ID.unique()`. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can\'t start with a special char. Max length is 36 chars.
     * @type {string}
     * @memberof TeamsCreateNewTeamRequest
     */
    'teamId': string;
    /**
     * Team name. Max length: 128 chars.
     * @type {string}
     * @memberof TeamsCreateNewTeamRequest
     */
    'name': string;
    /**
     * Array of strings. Use this param to set the roles in the team for the user who created it. The default role is **owner**. A role can be any string. Learn more about [roles and permissions](https://appwrite.io/docs/permissions). Maximum of 100 roles are allowed, each 32 characters long.
     * @type {Array<string>}
     * @memberof TeamsCreateNewTeamRequest
     */
    'roles'?: Array<string>;
}

