/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Team } from './team';

/**
 * Teams List
 * @export
 * @interface TeamList
 */
export interface TeamList {
    /**
     * Total number of teams documents that matched your query.
     * @type {number}
     * @memberof TeamList
     */
    'total': number;
    /**
     * List of teams.
     * @type {Array<Team>}
     * @memberof TeamList
     */
    'teams': Array<Team>;
}

