/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Token
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * Token ID.
     * @type {string}
     * @memberof Token
     */
    '$id': string;
    /**
     * Token creation date in ISO 8601 format.
     * @type {string}
     * @memberof Token
     */
    '$createdAt': string;
    /**
     * User ID.
     * @type {string}
     * @memberof Token
     */
    'userId': string;
    /**
     * Token secret key. This will return an empty string unless the response is returned using an API key or as part of a webhook payload.
     * @type {string}
     * @memberof Token
     */
    'secret': string;
    /**
     * Token expiration date in ISO 8601 format.
     * @type {string}
     * @memberof Token
     */
    'expire': string;
    /**
     * Security phrase of a token. Empty if security phrase was not requested when creating a token. It includes randomly generated phrase which is also sent in the external resource such as email.
     * @type {string}
     * @memberof Token
     */
    'phrase': string;
}

