/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Topic
 * @export
 * @interface Topic
 */
export interface Topic {
    /**
     * Topic ID.
     * @type {string}
     * @memberof Topic
     */
    '$id': string;
    /**
     * Topic creation time in ISO 8601 format.
     * @type {string}
     * @memberof Topic
     */
    '$createdAt': string;
    /**
     * Topic update date in ISO 8601 format.
     * @type {string}
     * @memberof Topic
     */
    '$updatedAt': string;
    /**
     * The name of the topic.
     * @type {string}
     * @memberof Topic
     */
    'name': string;
    /**
     * Total count of email subscribers subscribed to the topic.
     * @type {number}
     * @memberof Topic
     */
    'emailTotal': number;
    /**
     * Total count of SMS subscribers subscribed to the topic.
     * @type {number}
     * @memberof Topic
     */
    'smsTotal': number;
    /**
     * Total count of push subscribers subscribed to the topic.
     * @type {number}
     * @memberof Topic
     */
    'pushTotal': number;
    /**
     * Subscribe permissions.
     * @type {Array<string>}
     * @memberof Topic
     */
    'subscribe': Array<string>;
}

