/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersCreateTokenSessionRequest
 */
export interface UsersCreateTokenSessionRequest {
    /**
     * Token length in characters. The default length is 6 characters
     * @type {number}
     * @memberof UsersCreateTokenSessionRequest
     */
    'length'?: number;
    /**
     * Token expiration period in seconds. The default expiration is 15 minutes.
     * @type {number}
     * @memberof UsersCreateTokenSessionRequest
     */
    'expire'?: number;
}

