/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersUpdateTargetMessagingRequest
 */
export interface UsersUpdateTargetMessagingRequest {
    /**
     * The target identifier (token, email, phone etc.)
     * @type {string}
     * @memberof UsersUpdateTargetMessagingRequest
     */
    'identifier'?: string;
    /**
     * Provider ID. Message will be sent to this target from the specified provider ID. If no provider ID is set the first setup provider will be used.
     * @type {string}
     * @memberof UsersUpdateTargetMessagingRequest
     */
    'providerId'?: string;
    /**
     * Target name. Max length: 128 chars. For example: My Awesome App Galaxy S23.
     * @type {string}
     * @memberof UsersUpdateTargetMessagingRequest
     */
    'name'?: string;
}

