/*
Appwrite

Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

The version of the OpenAPI document: 1.5.0
Contact: team@appwrite.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Variable
 * @export
 * @interface Variable
 */
export interface Variable {
    /**
     * Variable ID.
     * @type {string}
     * @memberof Variable
     */
    '$id': string;
    /**
     * Variable creation date in ISO 8601 format.
     * @type {string}
     * @memberof Variable
     */
    '$createdAt': string;
    /**
     * Variable creation date in ISO 8601 format.
     * @type {string}
     * @memberof Variable
     */
    '$updatedAt': string;
    /**
     * Variable key.
     * @type {string}
     * @memberof Variable
     */
    'key': string;
    /**
     * Variable value.
     * @type {string}
     * @memberof Variable
     */
    'value': string;
    /**
     * Service to which the variable belongs. Possible values are \"project\", \"function\"
     * @type {string}
     * @memberof Variable
     */
    'resourceType': string;
    /**
     * ID of resource to which the variable belongs. If resourceType is \"project\", it is empty. If resourceType is \"function\", it is ID of the function.
     * @type {string}
     * @memberof Variable
     */
    'resourceId': string;
}

